version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: finvue-db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATA_DIR}/postgres_data:/var/lib/postgresql/data
    networks:
      - finvue-network
    user: ${USER_ID}:${GROUP_ID}

  backend:
    container_name: finvue-backend
    image: finvue-backend:latest
    env_file: .env
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=finvue-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - DatabaseConfig__Version=16
      - JwtConfig__KeyPath=${JWT_KEY_PATH}
      - JwtConfig__Issuer=${JWT_ISSUER}
      - JwtConfig__Audience=${JWT_AUDIENCE}
    networks:
      - finvue-network
    user: ${USER_ID}:${GROUP_ID}

  frontend:
    container_name: finvue-frontend
    image: finvue-frontend:latest
    env_file: .env
    ports:
      - "${FINVUE_WEB_UI_PORT}:80"
    depends_on:
      - backend
    networks:
      - finvue-network
    user: ${USER_ID}:${GROUP_ID}

networks:
  finvue-network:
    driver: bridge