name: Test, Build & Redeploy Api

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
jobs:
  test-api-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Dependencies
      run: |
        cd FinVue.Api/FinVue.Api
        dotnet restore
        
    - name: Build
      run: |
        cd FinVue.Api/FinVue.Api
        dotnet build
  test-ui-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.16'
        
    - name: Install dependencies
      run: |
        cd FinVue.UI
        npm ci
        
    - name: Build
      run: |
        cd FinVue.UI
        npm run config
        npm run build
  docker:
    name: Publish
    runs-on: ubuntu-latest
    needs: [test-api-build, test-ui-build]
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set VERSION
        run: echo "VERSION=$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Publish
        run: |
          cd app
          ./publish.sh